language: go
sudo: false
go:
  - 1.5

services:
  - mongodb

install:
  - go get -u github.com/golang/lint/golint
  - go get github.com/tools/godep

before_script:
  - FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
  - FIXED=$(go vet ./... 2>&1); if [ -n "${FIXED}" ]; then echo "go vet failed. $FIXED" && exit 1; fi
  - golint ./...

script:
  - ./test.sh